### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by sn0n** [doug2k1/nanogen#1]
I'm playing with nanogen, and I'm confused by what you mean with "Add build:prod script to build for GitHub Pages" ? 
I'm very new to javascript and nodejs, so I apologize if its basic.... 

and thanks for the awesome script tutorial!!

**Comment by sn0n** [comment]
I did find more info here : https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

But still confused by the usage here.

**Comment by doug2k1** [comment]
Hi! What that change does is add a new script "build:prod" the package.json that will save the generated site in the folder /docs (instead of /public, as the normal "build" script does).

This way the resulting site can be accessed at https://doug2k1.github.io/nanogen/ (the GitHub Pages feature expect the contents of the site to be in the /docs folder).

**Comment by sn0n** [comment]
Oh ok, awesome, thank you for the response.

**Comment by sn0n** [comment]
Also, using your generator on http://blokz.io/ 
I'm cleaning up the template and all the code and such, a work in progress, but once its done, blokz-gen will have credit listed clearly for your project here as the starting point. Thank you again for contributing this code and the medium article!

**Comment by doug2k1** [comment]
Wow, nice! Glad to hear this small project is being useful. 😄
